### PR TITLE
Add doc-id metadata

### PR DESCRIPTION
**Pull request by vbkaisetsu**
This branch adds `:doc-id` meta data that contains an ID of a hit document related to the index store.
This ID is useful for getting an `Explanation` objects of a document.

### CODE REVIEW

**Comment by federkasten** [comment]
@vbkaisetsu 

Sorry. This patch seems to conflict #16 changes.
Could you resolve or rebase the changes to make mergeable?

**Review by federkasten — CHANGES_REQUESTED** [review]
@vbkaisetsu 

Sorry. This patch seems to conflict #16 changes.
Could you resolve or rebase the changes to make mergeable?

**Comment by vbkaisetsu** [comment]
Fixed.

**Comment by federkasten** [comment]
Thanks!

**Pull request merged**
